src/main/java/de/samply/share/broker/model/db/tables/Contact.java
/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables;


import de.samply.share.broker.model.db.Indexes;
import de.samply.share.broker.model.db.Keys;
import de.samply.share.broker.model.db.Public;
import de.samply.share.broker.model.db.tables.records.ContactRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contact extends TableImpl<ContactRecord> {

    private static final long serialVersionUID = -1132822962;

    /**
     * The reference instance of <code>public.contact</code>
     */
    public static final Contact CONTACT = new Contact();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContactRecord> getRecordType() {
        return ContactRecord.class;
    }

    /**
     * The column <code>public.contact.id</code>.
     */
    public final TableField<ContactRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('contact_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.contact.portrait</code>.
     */
    public final TableField<ContactRecord, byte[]> PORTRAIT = createField("portrait", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.contact.title</code>.
     */
    public final TableField<ContactRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.contact.firstname</code>.
     */
    public final TableField<ContactRecord, String> FIRSTNAME = createField("firstname", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.contact.lastname</code>.
     */
    public final TableField<ContactRecord, String> LASTNAME = createField("lastname", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.contact.phone</code>.
     */
    public final TableField<ContactRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.contact.email</code>.
     */
    public final TableField<ContactRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.contact.organizationname</code>.
     */
    public final TableField<ContactRecord, String> ORGANIZATIONNAME = createField("organizationname", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.contact</code> table reference
     */
    public Contact() {
        this(DSL.name("contact"), null);
    }

    /**
     * Create an aliased <code>public.contact</code> table reference
     */
    public Contact(String alias) {
        this(DSL.name(alias), CONTACT);
    }

    /**
     * Create an aliased <code>public.contact</code> table reference
     */
    public Contact(Name alias) {
        this(alias, CONTACT);
    }

    private Contact(Name alias, Table<ContactRecord> aliased) {
        this(alias, aliased, null);
    }

    private Contact(Name alias, Table<ContactRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONTACT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContactRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CONTACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContactRecord> getPrimaryKey() {
        return Keys.CONTACT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContactRecord>> getKeys() {
        return Arrays.<UniqueKey<ContactRecord>>asList(Keys.CONTACT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Contact as(String alias) {
        return new Contact(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Contact as(Name alias) {
        return new Contact(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Contact rename(String name) {
        return new Contact(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Contact rename(Name name) {
        return new Contact(name, null);
    }
}

src/main/java/de/samply/share/broker/model/db/tables/pojos/User.java
/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 185951110;

    private Integer id;
    private String  username;
    private String  email;
    private String  name;
    private String  authid;
    private Integer contactId;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.username = value.username;
        this.email = value.email;
        this.name = value.name;
        this.authid = value.authid;
        this.contactId = value.contactId;
    }

    public User(
        Integer id,
        String  username,
        String  email,
        String  name,
        String  authid,
        Integer contactId
    ) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.name = name;
        this.authid = authid;
        this.contactId = contactId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAuthid() {
        return this.authid;
    }

    public void setAuthid(String authid) {
        this.authid = authid;
    }

    public Integer getContactId() {
        return this.contactId;
    }

    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(email);
        sb.append(", ").append(name);
        sb.append(", ").append(authid);
        sb.append(", ").append(contactId);

        sb.append(")");
        return sb.toString();
    }
}

src/main/java/de/samply/share/broker/control/SearchDetailsBean.java
/*
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Copyright (C) since 2016 The Samply Community
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */

package de.samply.share.broker.control;

import de.samply.share.broker.messages.Messages;
import de.samply.share.broker.model.db.enums.DocumentType;
import de.samply.share.broker.model.db.tables.pojos.Document;
import de.samply.share.broker.model.db.tables.pojos.Inquiry;
import de.samply.share.broker.model.db.tables.pojos.Site;
import de.samply.share.broker.model.db.tables.pojos.User;
import de.samply.share.broker.model.db.tables.pojos.UserSite;
import de.samply.share.broker.utils.db.DocumentUtil;
import de.samply.share.broker.utils.db.InquiryUtil;
import de.samply.share.broker.utils.db.SiteUtil;
import de.samply.share.broker.utils.db.UserSiteUtil;
import de.samply.share.broker.utils.db.UserUtil;
import de.samply.share.common.utils.ProjectInfo;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.application.ProjectStage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.Part;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.omnifaces.util.Ajax;
import org.omnifaces.util.Faces;

/**
 * A JSF Managed Bean that holds all details linked with an inquiry
 */
@ManagedBean(name = "searchDetailsBean")
@SessionScoped
public class SearchDetailsBean implements Serializable {

  private static final long serialVersionUID = -4671575946697123638L;
  private static final Logger logger = LogManager.getLogger(SearchDetailsBean.class);

  private static final String createEventhandlers = "createEventhandlers();";
  private static final String resetExposeFileinput = "$('#exposeUpload').fileinput('reset');";
  private static final String hideExposeFileinput = "$('#exposeBoxForm').hide();";
  private static final String showExposeFileinput = "$('#exposeBoxForm').show();";

  private static final String resetVoteFileinput = "$('#voteUpload').fileinput('reset');";
  private static final String hideVoteFileinput = "$('#voteBoxForm').hide();";
  private static final String showVoteFileinput = "$('#voteBoxForm').show();";

  private String inquiryName;
  private String inquiryDescription;
  private List<String> selectedSites;
  private List<String> resultTypes;
  private Inquiry inquiry;
  private Document expose;
  private Part newExpose;
  private Document vote;
  private Part newVote;
  private boolean cooperationAvailable;
  private boolean edit = false;
  private boolean validationActive = false;

  private String serializedQuery;

  @ManagedProperty(value = "#{loginController}")
  private LoginController loginController;

  @PostConstruct
  public void init() {
    selectedSites = new ArrayList<>();
    resultTypes = new ArrayList<>();
  }

  public String getInquiryName() {
    return inquiryName;
  }

  public void setInquiryName(String inquiryName) {
    this.inquiryName = inquiryName;
  }

  public String getInquiryDescription() {
    return inquiryDescription;
  }

  public void setInquiryDescription(String inquiryDescription) {
    this.inquiryDescription = inquiryDescription;
  }

  public List<String> getSelectedSites() {
    return selectedSites;
  }

  public void setSelectedSites(List<String> selectedSites) {
    this.selectedSites = selectedSites;
  }

  public List<String> getResultTypes() {
    return resultTypes;
  }

  public void setResultTypes(List<String> resultTypes) {
    this.resultTypes = resultTypes;
  }

  public Inquiry getInquiry() {
    return inquiry;
  }

  public void setInquiry(Inquiry inquiry) {
    this.inquiry = inquiry;
  }

  public Document getExpose() {
    return expose;
  }

  public void setExpose(Document expose) {
    this.expose = expose;
  }

  public Part getNewExpose() {
    return newExpose;
  }

  public void setNewExpose(Part newExpose) {
    this.newExpose = newExpose;
  }

  public Document getVote() {
    return vote;
  }

  public void setVote(Document vote) {
    this.vote = vote;
  }

  public Part getNewVote() {
    return newVote;
  }

  public void setNewVote(Part newVote) {
    this.newVote = newVote;
  }

  public boolean isCooperationAvailable() {
    return cooperationAvailable;
  }

  public void setCooperationAvailable(boolean cooperationAvailable) {
    this.cooperationAvailable = cooperationAvailable;
  }

  public boolean isEdit() {
    return edit;
  }

  public void setEdit(boolean edit) {
    this.edit = edit;
  }

  public boolean isValidationActive() {
    return validationActive;
  }

  public void setValidationActive(boolean validationActive) {
    this.validationActive = validationActive;
  }

  public String getSerializedQuery() {
    return serializedQuery;
  }

  public void setSerializedQuery(String serializedQuery) {
    this.serializedQuery = serializedQuery;
  }

  public LoginController getLoginController() {
    return loginController;
  }

  public void setLoginController(LoginController loginController) {
    this.loginController = loginController;
  }

  public List<Site> getSites() {
    return SiteUtil.fetchSites();
  }

  /**
   * Load the expose for the inquiry that is being created
   */
  private void loadExpose() {
    if (inquiry != null) {
      expose = DocumentUtil.fetchExposeByInquiry(inquiry);
    }
  }

  /**
   * Load the vote for the inquiry that is being created
   */
  private void loadVote() {
    if (inquiry != null) {
      vote = DocumentUtil.fetchVoteByInquiry(inquiry);
      setCooperationAvailable((vote != null) && (vote.getId() >= 0));
    }
  }

  /**
   * Load the expose with the given expose_id
   *
   * The id is transmitted via http request parameter
   */
  public void loadExposeWithId() {
    String id_string = Faces.getRequestParameter("expose_id");
    try {
      int id = Integer.parseInt(id_string);
      expose = DocumentUtil.getDocumentById(id);
      Ajax.oncomplete(createEventhandlers, hideExposeFileinput);
    } catch (NumberFormatException e) {
      logger.debug("Couldn't parse expose id" + id_string);
    }
  }

  /**
   * Load the vote with the given expose_id
   *
   * The id is transmitted via http request parameter
   */
  public void loadVoteWithId() {
    String id_string = Faces.getRequestParameter("vote_id");
    try {
      int id = Integer.parseInt(id_string);
      vote = DocumentUtil.getDocumentById(id);
      Ajax.oncomplete(createEventhandlers, hideVoteFileinput);
    } catch (NumberFormatException e) {
      logger.debug("Couldn't parse vote id" + id_string);
    }
  }

  /**
   * Export the expose of the current inquiry
   */
  public void exportExpose() throws IOException {
    if (expose != null && expose.getId() > 0) {
      ByteArrayOutputStream bos = DocumentUtil.getDocumentOutputStreamById(expose.getId());
      Faces.sendFile(bos.toByteArray(), "Exposee_" + inquiry + ".pdf", true);
    } else {
      logger.warn("Tried to export expose but couldn't find it");
    }
  }

  /**
   * Export the vote of the current inquiry
   */
  public void exportVote() throws IOException {
    if (vote != null && vote.getId() > 0) {
      ByteArrayOutputStream bos = DocumentUtil.getDocumentOutputStreamById(vote.getId());
      Faces.sendFile(bos.toByteArray(), "vote_" + inquiry + ".pdf", true);
    } else {
      logger.warn("Tried to export vote but couldn't find it");
    }
  }

  /**
   * Delete a document with the given elementId
   *
   * The id is transmitted via http request parameter
   */
  public void deleteDocument() {
    String documentIdString = Faces.getRequestParameter("elementId");
    try {
      int documentId = Integer.parseInt(documentIdString);
      DocumentType documentType = DocumentUtil.deleteDocument(documentId);
      if (documentType == DocumentType.DT_EXPOSE) {
        expose = null;
        Ajax.oncomplete(resetExposeFileinput, createEventhandlers, showExposeFileinput);
      } else if (documentType == DocumentType.DT_VOTE) {
        vote = null;
        Ajax.oncomplete(resetVoteFileinput, createEventhandlers, showVoteFileinput);
      } else {
        logger.debug("unknown document type");
      }
      logger.debug("Deleted document with id: " + documentId + " (type: " + documentType + ")");
    } catch (NumberFormatException e) {
      logger.warn("Could not parse expose id: " + documentIdString);
    }
  }

  /**
   * Clear all variables
   */
  public void clearStuff() {
    inquiryDescription = "";
    inquiryName = "";
    selectedSites = new ArrayList<>();
    resultTypes = new ArrayList<>();
    inquiry = null;
    serializedQuery = "";
    expose = null;

src/main/webapp/user/archivedInquiries.xhtml
<ui:composition template="/WEB-INF/templates/globalTemplate.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:wu="http://share.samply.de/webutils"
>

    <ui:define name="title">
        <h:outputText value="#{wu:getDisplayName()} - #{msg.archivedInquiries}"/>
    </ui:define>

    <ui:define name="additional-css">
        <h:outputStylesheet name="webjars/datatables/1.10.13/css/dataTables.bootstrap.min.css"/>
    </ui:define>

    <ui:define name="additional-js">
        <h:outputScript name="webjars/datatables/1.10.13/js/jquery.dataTables.min.js"/>
        <h:outputScript name="webjars/datatables/1.10.13/js/dataTables.bootstrap.min.js"/>
        <h:outputScript name="js/date-de.js" />
        <h:outputScript name="js/tables.js" />
    </ui:define>

    <ui:define name="page-header">
        <h1>#{msg.yourArchivedInquiries}</h1>
        <p>#{msg.archiveIntro}</p>
    </ui:define>

    <ui:define name="main-content">
        <h:form styleClass="form-inline" role="form" id="archivedInquiriesForm">
            <h:messages showDetail="true" showSummary="true" id="messages" globalOnly="true"/>

            <table class="table table-hover table-condensed" id="archivedInquiriesTable">
                <thead>
                <tr>
                    <th>#{msg.name}</th>
                    <th>Revision</th>
                    <th>#{msg.date}</th>
                    <th>#{msg.expires_at}</th>
                </tr>
                </thead>
                <tbody>
                <ui:repeat var="inq" value="#{inquiryController.outdatedInquiries}" varStatus="inqStatus">
                    <tr>
                        <td><h:link value="#{inq.label}" outcome="showInquiry">
                            <f:param name="inquiryId" value="#{inq.id}"/>
                        </h:link>
                        </td>
                        <td>#{inq.revision}</td>
                        <td>#{wu:convertTimestamp(inq.created)}</td>
                        <td>#{wu:isoToGermanDateString(inq.expires)}</td>
                    </tr>
                </ui:repeat>
                </tbody>
            </table>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/user/contact.xhtml
<ui:composition template="/WEB-INF/templates/globalTemplate.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
                xmlns:wu="http://share.samply.de/webutils"
>

    <ui:define name="metadata">
        <f:metadata>
            <f:event type="preRenderView" listener="#{loginController.reloadUserSite}"/>
        </f:metadata>
    </ui:define>

    <ui:define name="title">
        <h:outputText value="#{wu:getDisplayName()} - #{msg.contact_info}"/>
    </ui:define>


    <ui:define name="main-content">
        <div class="row">
            <div class="col-xs-6 col-xs-offset-3">
                <div class="page-header">
                    <h1>#{msg.profile}</h1>
                </div>
                <h:form class="form-horizontal" role="form" id="contactForm">
                    <div class="form-group">
                        <label for="title" class="col-sm-3 control-label">#{msg.title}</label>
                        <div class="col-sm-9">
                            <h:inputText id="title" name="title"
                                         value="#{loginController.contact.title}"
                                         placeholder="#{msg.title}" styleClass="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="firstName"
                               class="col-sm-3 control-label">#{msg.firstname}</label>
                        <div class="col-sm-9">
                            <h:inputText id="firstName" name="firstName"
                                         value="#{loginController.contact.firstname}"
                                         placeholder="#{msg.firstname}"
                                         styleClass="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="lastName" class="col-sm-3 control-label">#{msg.lastname}</label>
                        <div class="col-sm-9">
                            <h:inputText id="lastName" name="lastName"
                                         value="#{loginController.contact.lastname}"
                                         placeholder="#{msg.lastname}"
                                         styleClass="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">#{msg.email}</label>
                        <div class="col-sm-9">
                            <h:inputText id="email" name="email"
                                         value="#{loginController.contact.email}"
                                         placeholder="#{msg.email}" styleClass="form-control"
                                         disabled="disabled"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="phone" class="col-sm-3 control-label">#{msg.phone}</label>
                        <div class="col-sm-9">
                            <h:inputText id="phone" name="phone"
                                         value="#{loginController.contact.phone}"
                                         placeholder="#{msg.phone}"
                                         styleClass="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="organizationName"
                               class="col-sm-3 control-label">#{msg.contactLocation}</label>
                        <div class="col-sm-9">
                            <h:inputText id="organizationName" name="organizationName"
                                         value="#{loginController.contact.organizationname}"
                                         placeholder="#{msg.contactLocation}"
                                         styleClass="form-control"/>
                        </div>
                    </div>

                    <ui:fragment rendered="#{wu:getProjectName() == 'dktk'}">
                        <ui:param name="userSite" value="#{loginController.userSite}"/>
                        <div class="form-group">
                            <label for="organizationName"
                                   class="col-sm-3 control-label">#{msg.co_site}</label>

                            <ui:fragment rendered="#{empty userSite or !userSite.approved}">
                                <div class="col-sm-9">
                                    <h:selectOneMenu value="#{loginController.newSiteId}"
                                                     styleClass="form-control"
                                                     converter="omnifaces.SelectItemsConverter">
                                        <f:selectItem itemValue="#{null}" itemLabel=" "/>
                                        <f:selectItems value="#{loginController.sites}" var="site"
                                                       itemLabel="#{wu:getExtendedNamespace(site.name)}"
                                                       itemValue="#{site.id}"/>
                                    </h:selectOneMenu>
                                </div>
                                <ui:fragment rendered="#{not empty userSite}">
                                    <div class="col-sm-9 col-sm-offset-3 form-control-static">
                                        <i class="fa fa-info fa-fw"/>  #{msg.awaitingApproval}
                                    </div>
                                </ui:fragment>
                            </ui:fragment>
                            <ui:fragment rendered="#{not empty userSite and userSite.approved}">
                                <div class="col-sm-9 form-control-static">
                                    <h:outputText value="#{loginController.userSiteName}"/>
                                </div>
                            </ui:fragment>
                        </div>
                    </ui:fragment>

                    <ui:fragment
                            rendered="#{ (fn:containsIgnoreCase(wu:getProjectName(), 'osse')) or (fn:containsIgnoreCase(wu:getProjectName(), 'erdri')) }">
                        <div class="form-space"/>
                        <div class="form-group">
                            <label for="consentText"
                                   class="col-sm-3 control-label">#{msg.consent}</label>
                            <div class="col-sm-9">
                                <h:outputText id="consentText"
                                              value="#{loginController.latestConsent.content}"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="consent"
                                   class="col-sm-3 control-label">#{msg.iagree}</label>
                            <div class="col-sm-9">
                                <h:selectBooleanCheckbox id="consent" name="consent"
                                                         value="#{loginController.userConsent}"
                                                         styleClass="form-control"/>
                            </div>
                        </div>
                    </ui:fragment>

                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                            <h:commandLink styleClass="btn btn-md btn-success" value=""
                                           id="storeContact"
                                           actionListener="#{loginController.updateContact}">
                                <i class="fa fa-save fa-fw"/> #{msg.save_changes}
                            </h:commandLink>
                            <!--                                 <h:commandLink styleClass="btn btn-md btn-success" value="" id="storeContact" action="#{loginController.updateContact}" > -->
                            <!--                                     <i class="fa fa-save fa-fw" /> #{msg.save_changes} -->
                            <!--                                     <f:ajax execute="@form" render="@form" /> -->
                            <!--                                 </h:commandLink> -->
                        </div>
                    </div>
                </h:form>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-xs-offset-3">
                <h:messages showDetail="true" showSummary="true" id="messages" globalOnly="true"/>
            </div>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/user/editInquiry.xhtml
<ui:composition template="/WEB-INF/templates/globalTemplate.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:wu="http://share.samply.de/webutils">

    <ui:define name="metadata">
        <f:metadata>
            <f:viewParam name="inquiryId" value="#{inquiryController.selectedInquiryId}"/>
            <f:viewParam name="authHeader" value="#{inquiryController.authHeader}"/>
            <f:viewAction action="#{inquiryController.editInquiry}"/>
        </f:metadata>
    </ui:define>

    <ui:define name="title">
        <h:outputText value="#{wu:getDisplayName()} - #{msg.editInquiry}"/>
    </ui:define>

    <ui:define name="main-content">
        <h:outputText value="redirecting..."/>
    </ui:define>

</ui:composition>

src/main/webapp/user/submitted.xhtml
<ui:composition template="/WEB-INF/templates/globalTemplate.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:wu="http://share.samply.de/webutils">

    <ui:define name="title">
        <h:outputText value="#{wu:getDisplayName()} - #{msg.inquiry_stored}"/>
    </ui:define>

    <ui:define name="page-header">
        <h1>#{msg.inquiry_stored}</h1>
        <p>#{msg.querySubmitted}</p>
    </ui:define>

    <ui:define name="main-content">
        <h4>
            <h:outputLink value="dashboard.xhtml">#{msg.back_to_overview}</h:outputLink>
        </h4>
    </ui:define>

</ui:composition>